name: Build with tsc
on:
  push:
    branches:
      - main

jobs:
  run:
    name: Build with tsc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Cleanup
        run: rm package-lock.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          new_branch: dist
          push: '--force'
